export { default as HomePageScreen } from './HomePageScreen.vue'
export { default as SectionScreen } from './SectionScreen.vue'
export { default as NotFoundScreen } from './NotFoundScreen.vue'
export { default as MainScreen } from './MainScreen.vue'
export { default as DetailScreen } from './DetailScreen.vue'
export { default as MasterScreen } from './MasterScreen.vue'
